# Generated by Django 5.0.2 on 2024-10-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('accessories', models.CharField(max_length=50)),
                ('bookingamount', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
